<?php

declare(strict_types=1);

use App\Http\Controllers\Api\AuthController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Api Routes - Generated by Vemto
|--------------------------------------------------------------------------
|
| It is not recommended to edit this file directly. Although you can do so,
| it will generate a conflict on Vemto's next build.
|
*/

Route::name('api.')
    ->prefix('api')
    ->group(function () {
        Route::post('/login', [AuthController::class, 'login'])->name(
            'api.login'
        );

        Route::middleware('auth:sanctum')->group(function () {});
    });
