services:
  vito:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      NAME: "koamishin"
      EMAIL: "koamishin@example.com"
      PASSWORD: "password"
      APP_KEY: "base64:UodiJrx3DkcMlizmoimNlDn+yd4q5f2VbkBay19rJwM="
      APP_PORT: 80
      APP_URL: "http://localhost:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    volumes:
      - "vito-storage:/var/www/html/storage"
volumes:
  vito-storage:
    driver: local
